export const avatars = {
  Jude: "https://api.dicebear.com/9.x/adventurer/svg?seed=Jude",
  Chase: "https://api.dicebear.com/9.x/adventurer-neutral/svg?seed=Chase",
  Kimberly: "https://api.dicebear.com/9.x/avataaars/svg?seed=Kimberly",
  Mason: "https://api.dicebear.com/9.x/bottts/svg?seed=Mason",
  Jameson: "https://api.dicebear.com/9.x/bottts/svg?seed=Jameson",
  Maria: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Maria",
  George: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=George",
  Christian: "https://api.dicebear.com/9.x/dylan/svg?seed=Christian",
  Eden: "https://api.dicebear.com/9.x/miniavs/svg?seed=Eden",
  Sadie: "https://api.dicebear.com/9.x/miniavs/svg?seed=Sadie",
  Ryan: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Ryan",
  Katherine: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Katherine",
  Brian: "https://api.dicebear.com/9.x/bottts/svg?seed=Brian",
  Liam: "https://api.dicebear.com/9.x/bottts/svg?seed=Liam",
  Batman: "https://www.svgrepo.com/show/254105/batman.svg",
  Superman: "https://www.svgrepo.com/show/303409/superman-3-logo.svg",
  Spiderman: "https://www.svgrepo.com/show/303599/spider-man-4-logo.svg",
};

export const ACHIEVEMENT_DEFINITIONS = [
  {
    code: "10-TASK",
    name: "Jude",
    avatar: avatars.Jude,
    type: "TASK_COMPLETION",
    required: 10,
  },
  {
    code: "25-TASK",
    name: "Chase",
    avatar: avatars.Chase,
    type: "TASK_COMPLETION",
    required: 25,
  },
  {
    code: "5-REVIEW",
    name: "Mason",
    avatar: avatars.Mason,
    type: "TASK_REVIEW",
    required: 5,
  },
  {
    code: "10-REVIEW",
    name: "Jameson",
    avatar: avatars.Jameson,
    type: "TASK_REVIEW",
    required: 10,
  },
  {
    code: "25-REVIEW",
    name: "Brian",
    avatar: avatars.Brian,
    type: "TASK_REVIEW",
    required: 25,
  },
  {
    code: "5-ACCEPT",
    name: "Katherine",
    avatar: avatars.Katherine,
    type: "TASK_ACCEPT",
    required: 5,
  },
  {
    code: "10-ACCEPT",
    name: "Maria",
    avatar: avatars.Maria,
    type: "TASK_ACCEPT",
    required: 10,
  },
  {
    code: "25-ACCEPT",
    name: "Liam",
    avatar: avatars.Liam,
    type: "TASK_ACCEPT",
    required: 25,
  },
  {
    code: "100-TASK",
    name: "Superman",
    avatar: avatars.Superman,
    type: "TASK_COMPLETION",
    required: 100,
  },
  {
    code: "100-REVIEW",
    name: "Batman",
    avatar: avatars.Batman,
    type: "TASK_REVIEW",
    required: 100,
  },
  {
    code: "100-ACCEPT",
    name: "Spiderman",
    avatar: avatars.Spiderman,
    type: "TASK_ACCEPT",
    required: 100,
  },
];
